export { default as Header } from './Header'
export { default as Synthetic } from './Synthetic'
export { default as LuckyDraw } from './LuckyDraw'
export { default as Referral } from './Referral'
export { default as Footer } from './Footer'
export { default as Welcome } from './Welcome'
export { default as Partners } from './Partners'
export { default as Message } from './Message'
